// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Recipe struct {
	ID       int     `json:"id"`
	Title    string  `json:"title"`
	ImageURL *string `json:"imageUrl"`
}
